# Stage 1: Build app
FROM node:22 AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Nhúng tất cả biến môi trường cần thiết
ARG VITE_BACKEND_URL
ARG VITE_BACKEND_URL_DOCKER
ARG VITE_API_KEY
ARG VITE_AUTH_DOMAIN
ARG VITE_PROJECT_ID
ARG VITE_STORAGE_BUCKET
ARG VITE_MESSAGING_SENDER_ID
ARG VITE_APP_ID
ARG VITE_APP_ID_FACEBOOK
ARG VITE_APP_SECRET_FACEBOOK

ENV VITE_BACKEND_URL=$VITE_BACKEND_URL
ENV VITE_BACKEND_URL_DOCKER=$VITE_BACKEND_URL_DOCKER
ENV VITE_API_KEY=$VITE_API_KEY
ENV VITE_AUTH_DOMAIN=$VITE_AUTH_DOMAIN
ENV VITE_PROJECT_ID=$VITE_PROJECT_ID
ENV VITE_STORAGE_BUCKET=$VITE_STORAGE_BUCKET
ENV VITE_MESSAGING_SENDER_ID=$VITE_MESSAGING_SENDER_ID
ENV VITE_APP_ID=$VITE_APP_ID
ENV VITE_APP_ID_FACEBOOK=$VITE_APP_ID_FACEBOOK
ENV VITE_APP_SECRET_FACEBOOK=$VITE_APP_SECRET_FACEBOOK


RUN npm run build

# Stage 2: Serve with a lightweight web server (Nginx)
FROM nginx:alpine

# copy file build ra nginx
COPY --from=build /app/dist /usr/share/nginx/html

# copy file cấu hình nginx (tuỳ chọn)
# COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
