const TIME_OUT_LOADING = 200;
const LIMIT_PRODUCTS = 20;
const LIMIT_PER_PAGE = 5;
const LIMIT_SWIPER_PRODUCTS = 30;

const MIN_PRICE_PRODUCTS_SIDEBAR = 10000;
const MAX_PRICE_PRODUCTS_SIDEBAR = 1000000000;

export {
    TIME_OUT_LOADING,
    LIMIT_PRODUCTS,
    LIMIT_PER_PAGE,
    LIMIT_SWIPER_PRODUCTS,
    MIN_PRICE_PRODUCTS_SIDEBAR,
    MAX_PRICE_PRODUCTS_SIDEBAR,
};
